[project]
name = "k-colours"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
    "imageio>=2.37.0",
    "rich>=14.0.0",
    "scipy>=1.16.0",
]
