[project]
name = "kcolours"
version = "0.2.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
    "imageio>=2.37.0",
    "numpy>=2.3.1",
    "rich>=14.0.0",
    "scipy>=1.16.0",
]

[project.scripts]
kcolours = "kcolours.cli:run"
